name: Build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  tests:
    strategy:
      matrix:
        arch:
          - { name: 'x86_64-linux', runs-on: ubuntu-latest }
          - { name: 'x86_64-darwin', runs-on: macos-latest }
    name: ${{ matrix.arch.name }}
    runs-on: ${{ matrix.arch.runs-on }}
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixpkgs-22.05-darwin
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v14
      with:
        name: epic-eic
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix flake check --keep-going --print-build-logs --no-write-lock-file --cores `nproc || getconf _NPROCESSORS_ONLN`
