name: Docker deployment

on:
  push:
    branches:
      - master
      - pr/docker
    tags:
      - '*'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: '${{ github.actor }}'
        password: '${{ secrets.GITHUB_TOKEN }}'

    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixpkgs-22.05-darwin
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - uses: cachix/cachix-action@v10
      with:
        name: epic-eic
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - run: |
        nix build .#dockerImage --keep-going --print-build-logs --no-write-lock-file | tee nix_path
        docker load -i $(cat nix_path) | tee docker_load
        grep "Loaded image: " docker_load
        DOCKER_IMAGE=$(cut -d " " -f 3 docker_load)
        docker image tag $DOCKER_IMAGE ghcr.io/veprbl/epic-nix:latest
        docker image push ghcr.io/veprbl/epic-nix:latest
